aggregate:
    image: kharatsa/odkaggregate
    ports:
        - "8080:8080"
    links:
        - odkdb
    environment:
        # Supposed to have a default, but get an unbound variable in run.sh
        # line 33
        DB_CONTAINER_NAME: odkdb
        MYSQL_DATABASE: odk
        MYSQL_USER: odk
        MYSQL_PASSWORD: insecure
        ODK_HOSTNAME: ${HOSTIP}
        ODK_ADMIN_USERNAME: dav

odkdb:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: insecure
        MYSQL_DATABASE: odk
        MYSQL_USER: odk
        MYSQL_PASSWORD: insecure
